---
os: linux
dist: bionic

language: python
python: 3.7
cache: pip

install: "pip install $(pipenv lock --requirements)"
script: docs/build_docs.sh

notifications:
  irc:
    channels:
      - "ircs://chat.freenode.net:5597/#rit-foss-admin"
    template:
      - "[%{repository_name}:%{branch}@%{commit} - build #%{build_number}] CI %{result}! (%{build_url})"
    on_success: change
    on_failure: always
